Name = input("Enter your name: ")
Age = input("Enter your age: ")
College = input("Enter your college name: ")
print("-"*30)
print ("Name: ",Name,"\nAge: ", Age,"\nCollege: ", College)
print("-"*30)
print (f"Name: {Name} \nAge: {Age} \nCollege: {College}")
print("-"*30)
print ("Name: "+ Name + "\nAge: "+ Age + "\nCollege: "+ College)
print("-"*30)